export enum BuildingErrors {
  ID_MUST_BE_NUMBER = "ID_MUST_BE_NUMBER",
  REALTY_ID_MUST_BE_NUMBER = "REALTY_ID_MUST_BE_NUMBER",
  REQUIRED_ID = "REQUIRED_ID",
  REQUIRED_REALTY_ID = "REQUIRED_REALTY_ID",
  REQUIRED_TITLE = "REQUIRED_TITLE",
  TITLE_MUST_BE_STRING = "TITLE_MUST_BE_STRING",
}
