export enum RegisterInformationErrors {
  BUILDINGS_MUST_BE_ARRAY = "BUILDINGS_MUST_BE_ARRAY",
  REQUIRED_BUILDINGS = "REQUIRED_BUILDINGS",
  REALTIES_MUST_BE_ARRAY = "REALTIES_MUST_BE_ARRAY",
  REQUIRED_REALTIES = "REQUIRED_REALTIES",
  UNITS_MUST_BE_ARRAY = "UNITS_MUST_BE_ARRAY",
  REQUIRED_UNITS = "REQUIRED_UNITS",
}
